export const proxyDetails = [
    {
      id: "3112835",
      ip: "72.18.*.*",
      domain: "*.*.thehostingxperts.com",
      state: "CO",
      city: "Denver",
      isp: "Handy Networks, LLC",
      zip: "80202",
      speed: "632.8K",
      ping: 818,
      type: "DCH",
      added: "3 days",
      price: 0.40,
    },
    {
      id: "2229745",
      ip: "65.183.*.*",
      domain: "*.*.gctel.net",
      state: "ND",
      city: "Fargo",
      isp: "702 Communications",
      zip: "58103",
      speed: "1.3M",
      ping: 698,
      type: "ISP",
      added: "117 days",
      price: 0.50,
    },
  ];
  